### PR TITLE
Fix/xcpng fs diff.py

### PR DESCRIPTION
**Pull request by tescande**
Cosmetic changes and support for filenames containing special characters.

### CODE REVIEW

**Comment by stormi** [comment]
pycodestyle complains

**Comment by tescande** [comment]
> pycodestyle complains

Yep, saw that and I don't get it... All errors are `xcpng-fs-diff.py:1:XX:` like the file is only 1 line !

**Review by ydirson — APPROVED** [review]
lgtm

**Comment by stormi** [comment]
Naming your branch with an name ending with .py confused pycodestyle, who thinks the related ref in .git is a python file.

**Review by benjamreis — APPROVED** [review]

**Pull request merged**
