### PR TITLE
Stormi/update excluded test list

### PR DESCRIPTION
**Pull request by stormi**
Maintenance around the list of excluded jobs in jobs.py

### CODE REVIEW

**Review by benjamreis — APPROVED** [review]

**Review by ydirson — APPROVED** [review]
lgtm

**Comment by stormi** [comment]
@gduperrey Before I merge, could you run the next 8.2 and 8.3 full test suites from this branch?

**Comment by gduperrey** [comment]
Ful runs on our CI:
 * 8.2 :white_check_mark:
 * 8.3 :white_check_mark:

**Comment by stormi** [comment]
Thanks! Merging.

**Pull request merged**
