### PR TITLE
Add tests to check error when device is missing on LVM/EXT SRs

### PR DESCRIPTION
**Pull request by Wescoeur**
Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>

### CODE REVIEW

**Review by stormi — APPROVED** [review]
Looks good but maybe this would be a good candidate for extraction to a common lib for SR tests.

**Comment by Wescoeur** [comment]
I agree with that. There are helpers like `cold_migration_then_come_back` or `live_storage_migration_then_come_back` in `common.py`, but I'm not sure it's a good idea to put all helpers in a single file. We can probably create a new `storage.py` file or something like that. What do you think? @benjamreis @stormi

**Comment by benjamreis** [comment]
Yes a specific storage helper file would be good IMHO.
I'm not sure how much of the existing code should be mutualize though.
And probably in a separate PR as well.

**Comment by stormi** [comment]
Agreed. Yes if the file contains more than just this function, a separate PR will be better and then I'll merge this one. As you wish.

About the file location, I don't know what's best, put it in lib or in `tests/storage`. Probably `tests/storage` if it's just test code mutualized (we can still extract storage-related stuff from `lib/common.py` such as the SR class to a storage.py file... Or to per class files)

**Comment by Wescoeur** [comment]
Perfect, ok for `tests/storage`, I will create a new PR for that.

**Pull request merged**
